In [1]:
import numpy as np
import pandas as pd

from sklearn.metrics import accuracy_score

from shapiq_student.knn_explainer import KNNExplainer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from shapiq_student.knn_shapley2 import KNNExplainer2

In [2]:
df = pd.read_csv("shapiq_student/movie_dataset.csv")
train_df, test_df = train_test_split(df, test_size=0.4, random_state=42)
X_train = train_df[["fight_scenes","kiss_scenes"]].values.astype(np.float64)
y_train = train_df["label"].values
X_test = test_df[["fight_scenes","kiss_scenes"]].values.astype(np.float64)

y_test = test_df["label"].values

print(X_train)
print(X_test)

[[ 7.  1.]
 [ 0. 10.]
 [ 8.  3.]
 [ 9.  1.]
 [ 1.  7.]
 [ 8.  2.]]
[[ 2.  6.]
 [ 2.  8.]
 [10.  0.]
 [ 1.  9.]]


In [3]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
prediction = knn.predict(X_test)
accuracy = accuracy_score(y_test, prediction)
print(X_train)
print(X_test)

[[ 7.  1.]
 [ 0. 10.]
 [ 8.  3.]
 [ 9.  1.]
 [ 1.  7.]
 [ 8.  2.]]
[[ 2.  6.]
 [ 2.  8.]
 [10.  0.]
 [ 1.  9.]]


In [4]:
explainer = KNNExplainer(knn, X_train, y_train)

In [5]:
phi = explainer.explain(x=X_test)

TypeError: cannot unpack non-iterable int object

In [7]:
print(phi)

InteractionValues(
    index=SV, max_order=1, min_order=1, estimated=True, estimation_budget=None,
    n_players=2, baseline_value=0.0,
    Top 10 interactions:
        (0,): 0.0
        (1,): 0.0
)


Shapley Wang

In [4]:
explainer = KNNExplainer2(knn, X_train, y_train)
print(X_train)
print(X_test)

[[ 7.  1.]
 [ 0. 10.]
 [ 8.  3.]
 [ 9.  1.]
 [ 1.  7.]
 [ 8.  2.]]
[[ 2.  6.]
 [ 2.  8.]
 [10.  0.]
 [ 1.  9.]]


In [5]:
phi = explainer.explain(x_train_few=X_train, y_train_few=y_train, x_val_few=X_test, y_val_few=y_test, K=10, dis_metric='cosine')

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U9')) -> None

In [6]:
print(phi)

NameError: name 'phi' is not defined