In [1]:
import numpy as np
import pandas as pd
from networkx.algorithms.distance_measures import radius
from sklearn.metrics import accuracy_score

from shapiq_student.knn_explainer import KNNExplainer
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from shapiq_student.knn_explainer2 import KNNExplainer2
from shapiq_student.knn_explainer3 import KNNExplainer3

In [2]:
df = pd.read_csv("shapiq_student/movie_dataset.csv")
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)
X_train = train_df[["fight_scenes","kiss_scenes"]].values
y_train = train_df["label"].values
X_test = test_df[["fight_scenes","kiss_scenes"]].values
y_test = test_df["label"].values

In [3]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
prediction = knn.predict(X_test)
accuracy = accuracy_score(y_test, prediction)

In [4]:
from sklearn.neighbors import RadiusNeighborsClassifier

neigh = RadiusNeighborsClassifier(radius=4.0)

neigh.fit(X_train, y_train)
radius_prediction = neigh.predict(X_test)

# new approach

In [5]:
explainer = KNNExplainer3(knn, X_train, y_train)
print(y_test)
print(X_test)

[0 0]
[[2 6]
 [2 8]]


C:\Users\Alina\PycharmProjects\SEP_ALML_GroupD\.venv\Lib\site-packages\shapiq\explainer\_base.py:86: UserWarning: The `data` and the model must be compatible.
  warn(message)


In [6]:
phi = explainer.explain(x=X_test, y_test=y_test, radius=neigh.radius, K0=0, dis_metric = 'ah')

[0.         0.41666667 0.         0.16666667 0.         0.
 0.41666667 0.        ]


In [7]:
print("Shapley Werte:", phi)

Shapley Werte: InteractionValues(
    index=SV, max_order=1, min_order=1, estimated=True, estimation_budget=None,
    n_players=2, baseline_value=0.0,
    Top 10 interactions:
        (1,): 0.41666666666666663
        (0,): 0.0
)


# old approach|

In [8]:
explainer = KNNExplainer(knn, X_train, y_train)

C:\Users\Alina\PycharmProjects\SEP_ALML_GroupD\.venv\Lib\site-packages\shapiq\explainer\_base.py:86: UserWarning: The `data` and the model must be compatible.
  warn(message)


In [9]:
x_query = X_test[0], y_test[0]
print(x_query)

(array([2, 6]), np.int64(0))


In [10]:
phi = explainer.explain(x=X_test, radius=neigh.radius, x_query=x_query, num_classes=2)

4.0 4.0
(array([2, 6]), np.int64(0)) 2
2
shapley_values: [0.   0.25 0.   0.   0.   0.   0.25 0.  ]


In [11]:
print("Shapley Werte:", phi)

Shapley Werte: InteractionValues(
    index=SV, max_order=1, min_order=1, estimated=True, estimation_budget=None,
    n_players=2, baseline_value=0.0,
    Top 10 interactions:
        (1,): 0.25
        (0,): 0.0
)


In [12]:
x_query = X_test[1], y_test[1]
print(x_query)

(array([2, 8]), np.int64(0))


In [13]:
phi = explainer.explain(x=X_test, radius=neigh.radius, x_query=x_query, num_classes=2)

4.0 4.0
(array([2, 8]), np.int64(0)) 2
2
shapley_values: [0.         0.16666667 0.         0.16666667 0.         0.
 0.16666667 0.        ]


In [14]:
print("Shapley Werte:", phi)

Shapley Werte: InteractionValues(
    index=SV, max_order=1, min_order=1, estimated=True, estimation_budget=None,
    n_players=2, baseline_value=0.0,
    Top 10 interactions:
        (1,): 0.16666666666666666
        (0,): 0.0
)
